version: '3.8'

services:
  database:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
    ports:
      - 27017:27017
    expose:
      - 27017
    volumes:
      - ./scripts/mongo/:/docker-entrypoint-initdb.d/